image: node:12
cache:
  paths:
    - node_modules/

stages:
    - test

run-unit-test:
  stage: test
  script:
    - npm install
    - npm run test:ci
  artifacts:
    when: always
    paths:
      - coverage
    reports:
      junit:
        - junit.xml